## Import  library

In [2]:
import torch

## Check torch and CUDA version

In [10]:
print(torch.__version__)               # PyTorch version
print(torch.version.cuda)              # Corresponding CUDA version
print(torch.cuda.is_available())       # If CUDA is available

1.6.0
10.2
True


## Tensor 

https://pytorch.org/docs/stable/tensors.html

## Auto grad

https://pytorch.org/docs/stable/autograd.html?highlight=autograd#module-torch.autograd

## Vector opreation

In [6]:
import time

a = torch.ones(1000)
b = torch.ones(1000)

In [7]:
start = time.time()
c = torch.zeros(1000)
for i in range(1000):
    c[i] = a[i] + b[i]
end = time.time()
print(end - start)

0.026968002319335938


In [8]:
start = time.time()
d = a + b
end = time.time()
print(end - start)

0.0004048347473144531


## Data Selction  
 * `torch.index_select(x,dim,indices)` or `x.index_select(dim,indices)`

In [15]:
x = torch.randn(3, 4)
print(x)

indices = torch.tensor([0, 2])
print(torch.index_select(x, 0, indices))

print(torch.index_select(x, 1, indices))

tensor([[ 1.1135,  0.3615,  0.5208,  0.0534],
        [ 0.1684, -1.6925, -1.2004,  1.5689],
        [ 0.5202,  0.3780, -0.0521,  0.8711]])
tensor([[ 1.1135,  0.3615,  0.5208,  0.0534],
        [ 0.5202,  0.3780, -0.0521,  0.8711]])
tensor([[ 1.1135,  0.5208],
        [ 0.1684, -1.2004],
        [ 0.5202, -0.0521]])


## Sequential Usage

In [16]:
import torch.nn as nn

In [22]:
num_inputs =2 
# way1
net = nn.Sequential(
    nn.Linear(num_inputs, 1)
    #  ....
    )

# way2 : similar to Keras 
net = nn.Sequential()
net.add_module('linear', nn.Linear(num_inputs, 1))
# net.add_module ......


# way3
from collections import OrderedDict
net = nn.Sequential(OrderedDict([
          ('linear', nn.Linear(num_inputs, 1))
          # ......
        ]))

print(net)
print(net[0])


Sequential(
  (linear): Linear(in_features=2, out_features=1, bias=True)
)
Linear(in_features=2, out_features=1, bias=True)


## Keepdim

In [30]:
X = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(X.shape)
print(X.sum(dim=0, keepdim=False),X.sum(dim=0, keepdim=False).shape)
print(X.sum(dim=1, keepdim=False),X.sum(dim=1, keepdim=False).shape)
print(X.sum(dim=0, keepdim=True),X.sum(dim=0, keepdim=True).shape)
print(X.sum(dim=1, keepdim=True),X.sum(dim=0, keepdim=True).shape)

torch.Size([2, 3])
tensor([5, 7, 9]) torch.Size([3])
tensor([ 6, 15]) torch.Size([2])
tensor([[5, 7, 9]]) torch.Size([1, 3])
tensor([[ 6],
        [15]]) torch.Size([1, 3])


## Gather 


In [35]:
y_hat = torch.tensor([[0.1, 0.3, 0.6], 
                      [0.3, 0.2, 0.5]])
y = torch.LongTensor([0, 2]) 
new_y = y_hat.gather(1, y.view(-1, 1)) # pick the selected index and gather them together
new_y

tensor([[0.1000],
        [0.5000]])